background #212733
foreground #d9d7ce
cursor #ffcc66
selection_background #343f4c
color0 #191e2a
color8 #686868
color1 #ed8274
color9 #f28779
color2  #a6cc70
color10 #bae67e
color3  #fad07b
color11 #ffd580
color4  #6dcbfa
color12 #73d0ff
color5  #cfbafa
color13 #d4bfff
color6  #90e1c6
color14 #95e6cb
color7  #c7c7c7
color15 #ffffff
selection_foreground #212733

background_opacity 0.75
background_blur 20

window_margin_width 12
window_padding_width 7

allow_remote_control yes
listen_on unix:/tmp/mykitty

map ctrl+c copy_and_clear_or_interrupt
map ctrl+v paste_from_clipboard

# tab bar customization
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_edge bottom
tab_bar_align left
active_tab_font_style   bold
inactive_tab_font_style normal

map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+enter new_window_with_cwd
