general {
    lock_cmd = qs -p ~/.local/share/quickshell-lockscreen/lock_shell.qml
    before_sleep_cmd = qs -p ~/.local/share/quickshell-lockscreen/lock_shell.qml   # Changed!
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
}

# Lock the screen (runs your lock command directly)
listener {
    timeout = 700
    on-timeout = qs -p ~/.local/share/quickshell-lockscreen/lock_shell.qml
}

# Turn off the screen
listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
