general {
    lock_cmd = qs -p ~/.local/share/quickshell-lockscreen/lock_shell.qml
    before_sleep_cmd = loginctl lock-session    # command ran before sleep
    after_sleep_cmd = hyprctl dispatch dpms on  # command ran after sleep
}

# This is the missing piece!
listener {
    timeout = 10                                # this can be anything
    on-timeout = 
    on-resume = 
}

# The actual "lock" listener
# This ensures that whenever 'loginctl lock-session' is called, 
# hypridle actually executes your lock_cmd.
listener {
    on-timeout = loginctl lock-session
}
