general {
    lock_cmd = qs -p ~/.local/share/quickshell-lockscreen/lock_shell.qml
    before_sleep_cmd = qs -p ~/.local/share/quickshell-lockscreen/lock_shell.qml   # Changed!
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 300                           
    on-timeout = brightnessctl -s set 10   
    on-resume = brightnessctl -r          
}
listener {
    timeout = 600
    on-timeout = loginctl lock-session    
}

listener {
    timeout = 700                           
    on-timeout = hyprctl dispatch dpms off                            # screen off when timeout has passed
    on-resume = hyprctl dispatch dpms on && brightnessctl -r          # screen on when activity is detected after timeout has fired.
}

listener {
    timeout = 2500                           
    on-timeout = systemctl suspend                # suspend pc
}
