[pyprland]
plugins = ["scratchpads", "layout_center"]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class scratchpad"
class = "scratchpad"
size = "75% 60%"
unfocus = "hide"
lazy = "true"
allow_special_workspaces = true

[scratchpads.browser]
animation = "fromTop"
command = "min-browser"
class = "electron"
title = "Min"
match_by = "title"
size = "80% 70%"
unfocus = "hide"

[scratchpads.line]
animation = "fromTop"
command = "brave-origin-nightly --app=chrome-extension://ophjlpahpchlmihnnnihgmmeilfjmjjc/index.html"
class = "brave-ophjlpahpchlmihnnnihgmmeilfjmjjc__index.html-Default"
match_by = "title"
title = "LINE"
size = "70% 60%"
unfocus = "hide"
lazy = false

[layout_center]
margin = 30
offset = [0, 30]
next = "movefocus r"
prev = "movefocus l"
next2 = "movefocus d"
prev2 = "movefocus u"

