[pyprland]
plugins = ["scratchpads", "layout_center"]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class scratchpad"
class = "scratchpad"
size = "75% 60%"
unfocus = "hide"
lazy = "true"
allow_special_workspaces = true

[scratchpads.browser]
animation = "fromTop"
command = "min"
class = "Min"
size = "80% 70%"
unfocus = "hide"


[scratchpads.line]
animation = "fromTop"
command = "brave --app=chrome-extension://ophjlpahpchlmihnnnihgmmeilfjmjjc/index.html"
class = "brave-ophjlpahpchlmihnnnihgmmeilfjmjjc__index.html-Default"
size = "70% 60%"
unfocus = "hide"


[layout_center]
margin = 30
offset = [0, 30]
next = "movefocus r"
prev = "movefocus l"
next2 = "movefocus d"
prev2 = "movefocus u"

